name: build

on:
  pull_request:
    # We also want this workflow triggered if the 'Build all wheels'
    # label is added or present when PR is updated
    types:
      - opened
      - synchronize
      - labeled
  push:
    branches:
      - main
    tags:
      - "*"
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  build_quick:
    # This ensures that a couple of targets work fine in pull requests
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v2
    if: github.event_name == 'pull_request'
    with:
      upload_to_pypi: false
      upload_to_anaconda: false
      targets: |
        - cp311-manylinux_x86_64

  build:
    # This job builds the wheels and publishes them to PyPI for all
    # releases. For PRs with the "Build wheels" label, wheels are built,
    # but are not uploaded to PyPI.

    permissions:
      contents: none

    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v2

    if: ((github.event_name == 'release') && (github.event.action == 'released')) || contains(github.event.pull_request.labels.*.name, 'Build wheels')
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}

      # BUG: https://github.com/spacetelescope/spherical_geometry/issues/244
      # BUG: https://github.com/spacetelescope/spherical_geometry/issues/245
      targets: |
        # Linux wheels
        - cp3*-manylinux_x86_64
        - cp3*-musllinux_x86_64
        # FIXME: https://github.com/spacetelescope/spherical_geometry/issues/247
        #- cp3*-manylinux_aarch64

        # MacOS X wheels - we deliberately do not build universal2 wheels.
        # Note that the arm64 wheels are not actually tested so we
        # rely on local manual testing of these to make sure they are ok.
        - cp3*macosx_x86_64
        - cp3*macosx_arm64

        # Windows wheels
        - cp3*win32
        - cp3*win_amd64
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
